Complete hw 6
TimaFrolov/programmingSem4 pull request #10
Opened 2024-04-19 10:52 UTC by TimaFrolov

2024-04-19 13:44 UTC, DedSec256 requested changes

2024-04-19 13:44 UTC, DedSec256 commented on Hw6/Hw6/String.fs
> +            with _ ->
Обычно есть метод TryParse, чтобы не строить логику на эксепшенах (:

2024-04-19 13:44 UTC, DedSec256 commented on Hw6/Hw6/String.fs
> +        | None -> ""
Это здесь излишне, лучше возвращать option, а не прятать результат за какой-то пустой строкой

2024-04-19 13:44 UTC, DedSec256 commented on Hw6/Hw6.Tests/StringTests.fs
> +        let! x = "1"
а если число дробное?

2024-04-19 13:55 UTC, TimaFrolov commented on Hw6/Hw6/String.fs
> +        | None -> ""
Тут проблема в том, что если пытаться добавлять в это дело честный `option`, то это или ломает computation expression, или нельзя писать `let! x = "1"`, а по условию такое требуют :(
Если я что-то упустил и есть вариант, как использовать `option` - буду рад услышать

2024-04-19 13:59 UTC, TimaFrolov commented on Hw6/Hw6/String.fs
> +            with _ ->
Ок, переделал

2024-04-19 13:59 UTC, TimaFrolov commented on Hw6/Hw6.Tests/StringTests.fs
> +        let! x = "1"
Добавил тест

2024-04-19 14:57 UTC, DedSec256 commented on Hw6/Hw6/String.fs
> +        | None -> ""
Нет, не ломает, если правильно написать Bind и Return

2024-04-19 14:58 UTC, DedSec256 commented on Hw6/Hw6.Tests/StringTests.fs
> +        let! x = "1"
Вы можете сделать как захотите, но это нужно зафиксировать тестами.

2024-04-19 15:18 UTC, TimaFrolov commented on Hw6/Hw6/String.fs
> +        | None -> ""
А, окей, забыл, что перегрузки функций существуют :) 
Исправил

2024-04-19 15:22 UTC, DedSec256 commented on Hw6/Hw6/String.fs
> +        x |> Option.map (fun x -> this.Bind(x, f)) |> Option.flatten
А этот метод зачем?

2024-04-21 16:16 UTC, TimaFrolov commented on Hw6/Hw6/String.fs
> +        x |> Option.map (fun x -> this.Bind(x, f)) |> Option.flatten
:thinking: и правда не нужен. Убрал

2024-04-21 16:27 UTC, DedSec256 approved these changes

2024-05-13 10:21 UTC, merged