Hw 4 Task 1
TimaFrolov/programmingSem4 pull request #7
Opened 2024-03-22 13:04 UTC by TimaFrolov

2024-05-04 22:04 UTC, DedSec256 requested changes

2024-05-04 22:04 UTC, DedSec256 commented on Hw4/Task1.Tests/BraceSequenceTests.fs
> +let testCases =
нужно ещё проверить пустую строчку

2024-05-04 22:04 UTC, DedSec256 commented on Hw4/Task1/BraceSequence.fs
> +            | x when isClosingBrace x -> isBracePair (List.head acc, x) && helper (List.tail acc) tail
упадет на случае ")"

На это тоже нужно написать тест. Так же не рекомендую использовать более надежный паттерн-матчинг вместо List.head

2024-05-07 12:06 UTC, TimaFrolov commented on Hw4/Task1.Tests/BraceSequenceTests.fs
> +let testCases =
сделал

2024-05-07 12:07 UTC, TimaFrolov commented on Hw4/Task1/BraceSequence.fs
> +            | x when isClosingBrace x -> isBracePair (List.head acc, x) && helper (List.tail acc) tail
исправил

2024-05-11 03:33 UTC, DedSec256 commented on Hw4/Task1/BraceSequence.fs
> +        | None, _ -> false
```suggestion
        | None, x -> x = []
```

2024-05-11 07:27 UTC, merged